---
title: "Feedback Analysis Report"
author: "Helena Paterson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,  fig.align='center')
```

```{r main_analysis, echo=FALSE, warning = FALSE, message=FALSE}
library(markr)
library(tidyverse)


# for analysis loading Schedule A - this needs ot bein the same folder as this programme
schA <- read_csv("scheduleA.csv")

marks <- read_marks("marks.xlsx")

# adding schedule A to dat
marks <- left_join(marks, schA, "Grade")

# analysis overall distribution
desc_all <- summarise(marks, mean_grade = round(mean(Points),2), 
                      median_grade = round(median(Points),2))
# analysis per marker
desc_marker <- group_by(marks, marker) %>% 
  summarise(mean_grade = round(mean(Points),2), 
            median_grade = median(Points),
            StDevGrades = round(sd(Points),2))
```

## Grades for Overall Class

```{r, echo=FALSE}
# histogram overall
ggplot(marks, aes(Points)) + 
  geom_histogram(binwidth = 1) +
  scale_x_continuous(breaks = seq(0,22,1)) + 
  scale_y_continuous(breaks = seq(0,50,5)) +
  coord_cartesian(xlim = c(0,22), ylim = c(0,40), expand = FALSE) + 
  theme_classic()
```

```{r, echo=FALSE}
knitr::kable(desc_all, align = "c")
```


## Grades per Marker

```{r, echo=FALSE}
# histogram per marker

marks %>% 
  ggplot(aes(Points, fill = marker)) + 
  geom_histogram(binwidth = 1) + 
  guides(fill = FALSE) +
  scale_x_continuous(breaks = seq(0,22,2)) +
  scale_y_continuous(breaks = seq(0,15,1)) +
  labs(y = "Count per Grade", x = "22 point scale") +
  facet_wrap(~marker) +
  theme_classic()
```

```{r, echo=FALSE}
knitr::kable(desc_marker, align = "c")
```






